version: '3.8'

services:
  database:
    image: gimmitest/mysql-database:1.0.0
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: db-layer
    ports:
      - 3306:3306
    healthcheck:
      test: "exit 0"
  backend:
    image: gimmitest/spring-backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: be-layer
    ports:
      - 8484:8484
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: gimmitest/spring-frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fe-layer
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started